Update pullRequest.yml

diff --git a/.github/workflows/pullRequest.yml b/.github/workflows/pullRequest.yml
--- a/.github/workflows/pullRequest.yml
+++ b/.github/workflows/pullRequest.yml
@@ -48,16 +48,17 @@ jobs:
       - name: List Directory Contents
         run: ls -R
     
-      - name: Build IPA
+      - name: Build IPA0
         run: |
-              if [ -d "DemoCICD.xcodeproj" ]; then
-                xcodebuild -project DemoCICD.xcodeproj -scheme DemoCICD -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/DemoCICD.xcarchive
-                xcodebuild -exportArchive -archivePath $PWD/build/DemoCICD.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build/IPA
-              else
-                echo "Project not found. Listing directory contents:"
-                ls -R
-                exit 1
-              fi
+                if [ -d "DemoCICD.xcodeproj" ]; then
+                  xcodebuild clean -project DemoCICD.xcodeproj
+                  xcodebuild archive -project DemoCICD.xcodeproj -scheme DemoCICD -sdk iphoneos -configuration AppStoreDistribution -archivePath $PWD/build/DemoCICD.xcarchive
+                  xcodebuild -exportArchive -archivePath $PWD/build/DemoCICD.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build/IPA
+                else
+                  echo "Project not found. Listing directory contents:"
+                  ls -R
+                  exit 1
+                fi
     
       - name: Upload IPA to Artifacts
         if: success()
